In [167]:
import pandas as pd
import numpy as np
import xlwings as xw

In [199]:
import matplotlib.pyplot as plt
from matplotlib import font_manager, rc
from matplotlib import style
style.use('ggplot')
%matplotlib inline

font_name = font_manager.FontProperties(fname="c:/Windows/Fonts/malgun.ttf").get_name()
rc('font', family=font_name)
# 맥OS인 경우 위 두 줄을 입력하지 말고 아래 코드를 입력하세요
# rc('font', family='AppleGothic')
plt.rcParams['axes.unicode_minus'] = False

In [211]:
filename = 'C:/Users/LG/PythonDataWorkspace/DATA STUDY/240127 ONINE STORE/events.csv'

In [212]:
f = open(filename, 'r')  
f.readlines()[:5]

['event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session\n',
 '2020-09-24 11:57:06 UTC,view,1996170,2.14E+18,electronics.telephone,,31.9,1.52E+18,LJuJVLEjPT\n',
 '2020-09-24 11:57:26 UTC,view,139905,2.14E+18,computers.components.cooler,zalman,17.16,1.52E+18,tdicluNnRY\n',
 '2020-09-24 11:57:27 UTC,view,215454,2.14E+18,,,9.81,1.52E+18,4TMArHtXQy\n',
 '2020-09-24 11:57:33 UTC,view,635807,2.14E+18,computers.peripherals.printer,pantum,113.81,1.52E+18,aGFYrNgC08\n']

In [234]:
data = pd.read_csv(filename)

In [235]:
data["event_time"] = pd.to_datetime(data["event_time"].str[:19])
data

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2020-09-24 11:57:06,view,1996170,2.140000e+18,electronics.telephone,NaN,31.90,1.520000e+18,LJuJVLEjPT
1,2020-09-24 11:57:26,view,139905,2.140000e+18,computers.components.cooler,zalman,17.16,1.520000e+18,tdicluNnRY
2,2020-09-24 11:57:27,view,215454,2.140000e+18,NaN,NaN,9.81,1.520000e+18,4TMArHtXQy
3,2020-09-24 11:57:33,view,635807,2.140000e+18,computers.peripherals.printer,pantum,113.81,1.520000e+18,aGFYrNgC08
4,2020-09-24 11:57:36,view,3658723,2.140000e+18,NaN,cameronsino,15.87,1.520000e+18,aa4mmk0kwQ
...,...,...,...,...,...,...,...,...,...
481994,2020-12-21 22:13:24,view,4154736,2.140000e+18,computers.peripherals.keyboard,roccat,113.17,1.520000e+18,aIgZll0RBP
481995,2020-12-21 22:14:15,view,4156223,2.140000e+18,electronics.audio.headphone,borofone,15.56,1.520000e+18,2nhXNJGCeS
481996,2020-12-21 22:15:59,view,4102122,2.140000e+18,NaN,baseus,13.65,1.520000e+18,KCb5plBKl6
481997,2020-12-21 22:18:03,view,1413341,2.140000e+18,computers.components.cpu,amd,191.52,1.520000e+18,rLnNMr2xIw
481998,2020-12-21 22:18:12,view,1570050,2.140000e+18,computers.components.motherboard,asrock,87.40,1.520000e+18,rLnNMr2xIw

In [215]:
print("----------------------------------------------------------------------------")

for column in data.columns:
    if len(data[column].unique()) > 10:
        print(column + " unique값 확인")
        print(data[column].unique()[:10], "...")
        print(len(data[column].unique()), "개")
        print("----------------------------------------------------------------------------")
    else:
        print(column + " unique값 확인")
        print(data[column].unique())
        print(len(data[column].unique()), "개")
        print("----------------------------------------------------------------------------")

----------------------------------------------------------------------------
event_time unique값 확인
['2020-09-24T11:57:06.000000000' '2020-09-24T11:57:26.000000000'
 '2020-09-24T11:57:27.000000000' '2020-09-24T11:57:33.000000000'
 '2020-09-24T11:57:36.000000000' '2020-09-24T11:57:59.000000000'
 '2020-09-24T11:58:23.000000000' '2020-09-24T11:58:24.000000000'
 '2020-09-24T11:58:25.000000000' '2020-09-24T11:58:31.000000000'] ...
460681 개
----------------------------------------------------------------------------
event_type unique값 확인
['view' 'cart' 'purchase']
3 개
----------------------------------------------------------------------------
product_id unique값 확인
[1996170  139905  215454  635807 3658723  664325 3791349  716611  657859
  811491] ...
44732 개
----------------------------------------------------------------------------
category_id unique값 확인
[2.14e+18 2.15e+18 2.23e+18 2.22e+18 2.18e+18 2.17e+18]
6 개
----------------------------------------------------------------------------
category_code unique값 확인
['electronics.telephone' 'computers.components.cooler' nan
 'computers.peripherals.printer' 'construction.tools.saw'
 'computers.desktop' 'computers.network.router' 'electronics.video.tv'
 'auto.accessories.player' 'computers.components.motherboard'] ...
108 개
----------------------------------------------------------------------------
brand unique값 확인
[nan 'zalman' 'pantum' 'cameronsino' 'carver' 'd-link' 'ritmix' 'ricoh'
 'sony' 'kenwood'] ...
966 개
----------------------------------------------------------------------------
price unique값 확인
[ 31.9   17.16   9.81 113.81  15.87  52.33 215.41  53.14  34.17  33.32] ...
11528 개
----------------------------------------------------------------------------
user_id unique값 확인
[1.52e+18]
1 개
----------------------------------------------------------------------------
user_session unique값 확인
['LJuJVLEjPT' 'tdicluNnRY' '4TMArHtXQy' 'aGFYrNgC08' 'aa4mmk0kwQ'
 'vnkdP81DDW' 'J1t6sIYXiV' 'kVBeYDPcBw' 'HEl15U7JVy' 'F3VB9LYp39'] ...
278521 개
----------------------------------------------------------------------------

In [216]:
print("---------------------------")

row_count = data.shape[0]

for column in data.columns:
    null_count = data[column].isnull().sum()
    if null_count > 0:
        print(column + " 결측치 비율")
        print(round(null_count / row_count * 100, 2), "%")
        print("---------------------------")
    else:
        pass

---------------------------
category_code 결측치 비율
28.76 %
---------------------------
brand 결측치 비율
24.87 %
---------------------------
user_session 결측치 비율
0.03 %
---------------------------

In [236]:
data_copy_1 = data

group_data = data_copy_1.groupby(["user_session", "event_type"]).agg(datetime = ("event_time", "min"))

temp_df = pd.DataFrame(data_copy_1['event_type'].unique(), columns = ["event_type"])
temp_df["step"] = [1, 2, 3]
temp_df.set_index("event_type", append = False, inplace = True)

merge_data = pd.merge(group_data, temp_df, left_on = "event_type", right_index = True)

pivot_data = merge_data.reset_index().pivot(index = ["user_session"], columns = "step", values = "datetime")

pivot_data.columns = temp_df.index
pivot_data

event_type                                          view cart purchase
user_session
000c34fa-991f-442a-8e07-8c472269bec6 2020-09-30 17:52:02  NaT      NaT
001P7lK0Pt                           2020-11-06 01:25:30  NaT      NaT
002DmERG1w                           2020-09-26 18:59:06  NaT      NaT
003QqC0jk0                           2020-10-25 15:23:25  NaT      NaT
003pEktS1X                           2020-11-02 18:11:24  NaT      NaT
...                                                  ...  ...      ...
zztce59nU2                           2020-10-29 18:02:28  NaT      NaT
zztjHPLepJ                           2020-11-14 18:31:44  NaT      NaT
zzvjiUwHhM                           2020-12-18 10:31:55  NaT      NaT
zzxnA0nWEY                           2020-11-17 11:34:14  NaT      NaT
zzy0qXtxYX                           2020-11-08 17:08:01  NaT      NaT

[278520 rows x 3 columns]

In [237]:
step_count = [pivot_data[event].notnull().sum() for event in pivot_data.columns]

print("event별 횟수")
for num, event in enumerate(step_count):
    print(pivot_data.columns[num], " : ", event, "회")
    
print("")

print("event별 전환율")
for num, event in enumerate(step_count[1:]):
    step_rate = round(event / step_count[num] * 100, 2)
    print(pivot_data.columns[num+1], " 전환율 : ", step_rate, "%")

event별 횟수
view  :  277475 회
cart  :  20870 회
purchase  :  12534 회

event별 전환율
cart  전환율 :  7.52 %
purchase  전환율 :  60.06 %

In [243]:
data["category_code"].value_counts().head(50)

electronics.telephone              27193
computers.components.videocards    23775
computers.peripherals.printer      20940
stationery.cartrige                18275
computers.components.cpu           14391
                                   ...
auto.accessories.immobilizer          31
furniture.living_room.shelving        26
furniture.living_room.chair           26
furniture.bathroom.bath               21
furniture.bedroom.blanket             17
Name: category_code, Length: 100, dtype: int64

In [244]:
data_copy_2 = data

# 결측값 제거
data = data_copy_2.drop("user_id", axis = 1)
data = data_copy_2.dropna(how='any')

# session별 / category별 / brand별 funnel 확인
group_data = data_copy_2.groupby(["user_session", "category_code", "brand", "event_type"]).agg(datetime = ("event_time", "min"))

temp_df = pd.DataFrame(data_copy_2['event_type'].unique(), columns = ["event_type"])
temp_df["step"] = [1, 2, 3]
temp_df.set_index("event_type", append = False, inplace = True)

merge_data = pd.merge(group_data, temp_df, left_on = "event_type", right_index = True)

pivot_data = merge_data.reset_index().pivot(index = ["user_session", "category_code", "brand"], columns = "step", values = "datetime")

pivot_data.columns = temp_df.index
pivot_data

event_type                                                                                    view  \
user_session                         category_code                    brand
000c34fa-991f-442a-8e07-8c472269bec6 electronics.tablet               xiaomi   2020-09-30 17:52:02
001P7lK0Pt                           electronics.audio.headphone      samsung  2020-11-06 01:25:43
002DmERG1w                           computers.components.tv_tuner    d-color  2020-09-26 18:59:06
003pEktS1X                           stationery.cartrige              cactus   2020-11-02 18:11:24
0041IWrUEl                           appliances.sewing_machine        janome   2020-10-28 07:13:45
...                                                                                            ...
zztRHEozV0                           computers.components.videocards  msi      2020-09-30 12:32:12
                                                                      sapphire 2020-09-30 12:31:41
zztSfMn54L                           electronics.clocks               amazfit  2020-10-03 22:39:48
zztjHPLepJ                           electronics.telephone            palmexx  2020-11-14 18:31:44
zzy0qXtxYX                           computers.components.motherboard asus     2020-11-08 17:08:01

event_type                                                                     cart  \
user_session                         category_code                    brand
000c34fa-991f-442a-8e07-8c472269bec6 electronics.tablet               xiaomi    NaT
001P7lK0Pt                           electronics.audio.headphone      samsung   NaT
002DmERG1w                           computers.components.tv_tuner    d-color   NaT
003pEktS1X                           stationery.cartrige              cactus    NaT
0041IWrUEl                           appliances.sewing_machine        janome    NaT
...                                                                             ...
zztRHEozV0                           computers.components.videocards  msi       NaT
                                                                      sapphire  NaT
zztSfMn54L                           electronics.clocks               amazfit   NaT
zztjHPLepJ                           electronics.telephone            palmexx   NaT
zzy0qXtxYX                           computers.components.motherboard asus      NaT

event_type                                                                     purchase
user_session                         category_code                    brand
000c34fa-991f-442a-8e07-8c472269bec6 electronics.tablet               xiaomi        NaT
001P7lK0Pt                           electronics.audio.headphone      samsung       NaT
002DmERG1w                           computers.components.tv_tuner    d-color       NaT
003pEktS1X                           stationery.cartrige              cactus        NaT
0041IWrUEl                           appliances.sewing_machine        janome        NaT
...                                                                                 ...
zztRHEozV0                           computers.components.videocards  msi           NaT
                                                                      sapphire      NaT
zztSfMn54L                           electronics.clocks               amazfit       NaT
zztjHPLepJ                           electronics.telephone            palmexx       NaT
zzy0qXtxYX                           computers.components.motherboard asus          NaT

[173478 rows x 3 columns]

In [245]:
purchase_data = pivot_data[pivot_data["purchase"].notnull() == True].dropna(how = "any")
purchase_data

,,event_type,view,cart,purchase
user_session,category_code,brand,,,
00RLUrffvt,computers.ebooks,pocketbook,2020-11-10 18:18:45,2020-11-10 19:02:50,2020-11-10 19:03:56
02715328-95e2-4132-9178-5185f2436219,electronics.video.tv,starwind,2020-11-18 14:33:20,2020-11-18 14:34:11,2020-11-18 14:35:31
02SUh9p1xh,stationery.cartrige,hp,2020-11-27 08:13:10,2020-11-27 08:13:25,2020-11-27 08:17:19
02cmqEzaTl,computers.components.motherboard,asus,2020-10-01 14:23:49,2020-10-01 14:25:07,2020-10-01 14:26:17
043447a5-d6af-4a3f-ad8f-ed8c455a2b17,computers.components.tv_tuner,perfeo,2020-09-24 13:42:18,2020-09-24 13:42:34,2020-09-24 13:43:30
...,...,...,...,...,...
zwvvEJqZZD,computers.components.motherboard,asus,2020-09-30 06:23:28,2020-09-30 06:23:51,2020-09-30 06:24:31
zxwd9oqTKx,electronics.telephone,sirius,2020-11-16 17:51:09,2020-11-16 17:51:54,2020-11-16 17:53:01
zyCwRFIila,electronics.telephone,alcatel,2020-10-15 12:01:33,2020-11-01 07:33:00,2020-11-01 07:37:54
zzM79K5zNh,electronics.telephone,digma,2020-12-21 11:47:55,2020-12-21 11:48:18,2020-12-21 11:49:23
zzfih3qogN,stationery.cartrige,canon,2020-11-12 08:19:48,2020-11-12 08:21:36,2020-11-12 08:22:17

In [323]:
purchase = purchase_data.reset_index()
purchase_group = purchase.groupby(["category_code", "brand"]).count().reset_index()
purchase_group = purchase_group.drop(purchase_group.columns[2:5], axis = 1)

best_brand = pd.DataFrame(columns = ["category_code", "brand", "purchase"])

for category in purchase_group["category_code"].unique():
    
    temp_1 = purchase_group[purchase_group["category_code"] == category]
    temp_2 = temp_1[temp_1["purchase"] == temp_1["purchase"].max()]
    best_brand = pd.concat((best_brand, temp_2), ignore_index = True)
    
best_brand

                        category_code     brand purchase
0                     accessories.bag    targus        4
1   appliances.environment.air_heater   polaris        3
2       appliances.environment.vacuum     topon       38
3                     appliances.iron   philips        2
4          appliances.kitchen.blender   polaris        2
..                                ...       ...      ...
85                      sport.bicycle     digma        1
86                 stationery.battery  duracell        3
87                stationery.cartrige        hp      202
88                   stationery.paper    lomond       17
89                 stationery.stapler     p.i.t       12

[90 rows x 3 columns]

In [324]:
purchase_data = pivot_data[pivot_data["purchase"].notnull() == True].dropna(how = "any")

purchase = purchase_data.reset_index()
purchase_group = purchase.groupby(["category_code", "brand"]).count().reset_index()
purchase_group = purchase_group.drop(purchase_group.columns[2:5], axis = 1)

best_brand = pd.DataFrame(columns = ["category_code", "brand", "purchase"])

for category in purchase_group["category_code"].unique():
    
    temp_1 = purchase_group[purchase_group["category_code"] == category]
    temp_2 = temp_1[temp_1["purchase"] == temp_1["purchase"].max()]
    best_brand = pd.concat((best_brand, temp_2), ignore_index = True)
    
best_brand

                        category_code     brand purchase
0                     accessories.bag    targus        4
1   appliances.environment.air_heater   polaris        3
2       appliances.environment.vacuum     topon       38
3                     appliances.iron   philips        2
4          appliances.kitchen.blender   polaris        2
..                                ...       ...      ...
85                      sport.bicycle     digma        1
86                 stationery.battery  duracell        3
87                stationery.cartrige        hp      202
88                   stationery.paper    lomond       17
89                 stationery.stapler     p.i.t       12

[90 rows x 3 columns]